export const Designs = [
  {
    id: 1,
    title: "Modern SaaS Landing Page",
    category: "SaaS",
    author: "John UI",
    price: 49,
    rating: 4.8,
    image: "https://picsum.photos/id/1015/600/400",
  },
  {
    id: 2,
    title: "Creative Portfolio Website",
    category: "Portfolio",
    author: "Emma Design",
    price: 29,
    rating: 4.6,
    image: "https://picsum.photos/id/1011/600/400",
  },
  {
    id: 3,
    title: "E-commerce Storefront",
    category: "E-commerce",
    author: "Alex Studio",
    price: 59,
    rating: 4.9,
    image: "https://picsum.photos/id/1018/600/400",
  },
  {
    id: 4,
    title: "Digital Agency Website",
    category: "Agency",
    author: "Creative Labs",
    price: 39,
    rating: 4.7,
    image: "https://picsum.photos/id/1025/600/400",
  },
  {
    id: 5,
    title: "Startup Landing Page",
    category: "Startup",
    author: "NextGen UI",
    price: 45,
    rating: 4.5,
    image: "https://picsum.photos/id/1035/600/400",
  },
  {
    id: 6,
    title: "Minimal Blog Layout",
    category: "Blog",
    author: "Simple Themes",
    price: 19,
    rating: 4.3,
    image: "https://picsum.photos/id/1041/600/400",
  },
  {
    id: 7,
    title: "Corporate Business Website",
    category: "Business",
    author: "Pro Web Co.",
    price: 55,
    rating: 4.8,
    image: "https://picsum.photos/id/1050/600/400",
  },
  {
    id: 8,
    title: "Dark Theme Dashboard UI",
    category: "Dashboard",
    author: "UX Masters",
    price: 69,
    rating: 4.9,
    image: "https://picsum.photos/id/1060/600/400",
  },
  {
    id: 9,
    title: "NFT Marketplace Design",
    category: "Marketplace",
    author: "Crypto Studio",
    price: 79,
    rating: 4.6,
    image: "https://picsum.photos/id/1070/600/400",
  },
  {
    id: 10,
    title: "Personal Branding Website",
    category: "Personal",
    author: "Brandify",
    price: 25,
    rating: 4.4,
    image: "https://picsum.photos/id/1080/600/400",
  },
];
